# Generated by Django 5.2.3 on 2025-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminUID', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=89)),
                ('last_name', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=90, unique=True)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null='True')),
                ('phone', models.CharField(max_length=10, null='True')),
                ('desc', models.TextField(null='True')),
                ('var', models.TextField(null='True')),
                ('var2', models.TextField(null='True')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=89)),
                ('last_name', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=90, unique=True)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
    ]
