# Generated by Django 5.2.3 on 2025-09-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='admindata',
            old_name='name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='admindata',
            old_name='adminUID',
            new_name='admin_username',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='last_name',
        ),
    ]
