# Generated by Django 5.2.3 on 2025-09-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_email_admindata_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindata',
            name='admin_name',
        ),
    ]
