# Generated by Django 4.2 on 2025-10-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_admindata_admin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='var',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='var2',
        ),
    ]
